### ISSUE TITLE
Automate device configuration

### ISSUE THREAD

**Issue by dspinellis** [eellak/epidose#40]
* [x] Python package installation (as documented in the *README* file)
* [x] `wpa_supplicant` (see #24)
* [ ] `/etc/network/interfaces.d/wlan0` (see #24)
* [ ] `/sbin/hwclock` (see #39)

**Comment by stefanos1316** [comment]
- [x] Create a new user with username _epidose_
- [x] Establish passwordless ssh using the authorization keys
- [x] Switch to user _epidose_
- [x] Remove default user (_pi_)
